name = "PlanetOrbits"
uuid = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"
authors = ["William Thompson <will.thompson@outlook.com>", "Jensen Lawrence"]
version = "0.10.2"

[deps]
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
PlanetOrbitsEnzymeExt = "Enzyme"
PlanetOrbitsForwardDiffExt = "ForwardDiff"
PlanetOrbitsMakieExt = "Makie"

[compat]
AstroTime = "0.7"
ChainRulesCore = "1"
CoordinateTransformations = "0.6"
DiffRules = "1"
Enzyme = "0.11, 0.12, 0.13"
ForwardDiff = "0.10"
julia = "^1.9"
NamedTupleTools = "0.13, 0.14"
PrecompileTools = "1.1.2"
RecipesBase = "1.2"
StaticArrays = "1.3"
Roots = "2.1"


[extras]
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "FiniteDiff", "ForwardDiff", "Enzyme", "Zygote", "ReverseDiff"]
