name = "PlanetOrbits"
uuid = "fd6f9641-d78f-43ce-a379-ceb0bddb468a"
authors = ["William Thompson <will.thompson@outlook.com>", "Jensen Lawrence"]
version = "0.2.0"

[deps]
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
AstroTime = "0.7"
ChainRulesCore = "1"
CoordinateTransformations = "0.6"
Distributions = "0.25"
NamedTupleTools = "0.13, 0.14"
RecipesBase = "1.2"
Requires = "1.3"
StaticArrays = "1.3"
julia = "^1.6"

[extras]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FiniteDiff", "ForwardDiff"]
